=== Prive1/KSRM/ksrm/Models/ModelSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/ModelSchema" xmlns:tns="http://www.example.org/ModelSchema" elementFormDefault="qualified">

    <element name="Model">
    	<complexType>
    		<sequence>
	        	<element name="Name" type="string"></element> 
	            <element name="Button" maxOccurs="unbounded">
	    			<complexType>
	    				<sequence>
	    					<element name="ButtonName" type="string" />
	    					<element  name="ButtonNr" type="positiveInteger" />
	    				</sequence>
	    			</complexType> 
	    		</element>
    		</sequence>
    	</complexType>
    </element>
</schema>

=== Prive1/KSRM/ksrm/Models/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Model xmlns:tns="http://www.example.org/ModelSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ModelSchema ModelSchema.xsd ">
  <tns:Name>FirstModel</tns:Name>
  <tns:Button>
    <tns:ButtonName>Button 1</tns:ButtonName>
    <tns:ButtonNr>1</tns:ButtonNr>
  </tns:Button>
   <tns:Button>
    <tns:ButtonName>Button 2</tns:ButtonName>
    <tns:ButtonNr>2</tns:ButtonNr>
  </tns:Button>
   <tns:Button>
    <tns:ButtonName>Button 3</tns:ButtonName>
    <tns:ButtonNr>3</tns:ButtonNr>
  </tns:Button>
</tns:Model>
